//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel;



namespace AplicacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugadores
    {
        public int id { get; set; }
        [DisplayName("Nombre")]
        public string name { get; set; }
        [DisplayName("Apellido")]
        public string lastName { get; set; }
        [DisplayName("Equipo")]
        public string team { get; set; }
        [DisplayName("Posicion")]
        public string position { get; set; }
    }
}
